### ISSUE TITLE
'_MultiProcessingDataLoaderIter' object has no attribute 'dataset'

### ISSUE THREAD

**Issue by ffiioonnaa** [hassony2/obman_train#16]
Hi，
Thanks for your excellent work! I encountered an error while running the training code 
ProcessingTraceback (most recent call last):
```
  File "traineval.py", line 418, in <module>
    main(args)
  File "traineval.py", line 298, in main
    fig=fig,
  File "/home/zhao/obman_train/mano_train/netscripts/epochpass3d.py", line 71, in epoch_pass
    for batch_idx, (sample) in enumerate(loader):
  File "/home/zhao/obman_train/mano_train/datautils.py", line 18, in __next__
    if isinstance(loader.dataset, Subset):
AttributeError: '_MultiProcessingDataLoaderIter' object has no attribute 'dataset'
```
and I try to use  ' loader._dataset' instead of 'loader.dataset'  ,then I met another error

```
  File "/home/zhao/obman_train/mano_train/networks/branches/manobranch.py", line 181, in forward
    root_palm=root_palm,
  File "/home/zhao/anaconda3/envs/obman_train/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhao/anaconda3/envs/obman_train/lib/python3.7/site-packages/manopth/manolayer.py", line 141, in forward
    self.th_hands_mean + th_full_hand_pose
RuntimeError: The size of tensor a (45) must match the size of tensor b (3) at non-singleton dimension 3
```
![2019-12-16 14-51-34屏幕截图](https://user-images.githubusercontent.com/34903836/70885381-aef54b00-2013-11ea-963d-2ef4090dabf9.png)
![2019-12-16 14-52-17屏幕截图](https://user-images.githubusercontent.com/34903836/70885405-b3216880-2013-11ea-9db4-fe57ecccf1b2.png)

**Comment by toharl** [comment]
pytorch 1.1.0 has solved the issue for me
