### ISSUE TITLE
FileNotFoundError surface_points.pkl

### ISSUE THREAD

**Issue by ethanhe42** [hassony2/obman_train#22]
I ran into this error when I try `python traineval.py --atlas_predict_trans --atlas_predict_scale --atlas_mesh --mano_use_shape --mano_use_pca --freeze_batchnorm --atlas_separate_encoder`
Am I missing something? I don't see `surface_points.pkl` in shapenetcore folder
```
Saved options to checkpoints/debug/opt.txt
/private/home/yihuihe/.conda/envs/con37/lib/python3.7/site-packages/manopth/manolayer.py:72: UserWarning:

The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning
 will be suppressed for the rest of this program. (Triggered internally at  /opt/conda/conda-bld/pytorch_1595629403081/work/torch/csrc/utils/tensor_numpy.cpp:141.)

Using 2 GPUs !
Cached information for dataset obman loaded from data/cache/obman/train_None_mode_all.pkl
Final dataset size: 141550
Cached information for dataset obman loaded from data/cache/obman/train_None_mode_all.pkl
Using lr 0.0001
epoch: 0
ProcessingTraceback (most recent call last):
  File "/private/home/yihuihe/obman_train/handobjectdatasets/handataset.py", line 417, in __getitem__
    sample = self.get_sample(idx, self.queries)
  File "/private/home/yihuihe/obman_train/handobjectdatasets/handataset.py", line 311, in get_sample
    idx, point_nb=self.point_nb
  File "/private/home/yihuihe/obman_train/handobjectdatasets/obman.py", line 458, in get_objpoints3d
    with open(model_path, "rb") as obj_f:
FileNotFoundError: [Errno 2] No such file or directory: 'datasymlinks/ShapeNetCore.v2/02880940/9a6cec1cfca7e8b5ebc583f22bd58b85/models/surface_points.pkl'
Encountered error processing sample 132369
```

**Comment by hassony2** [comment]
Dear @yihui-he ,

Does [the answer](https://github.com/hassony2/obman_train/issues/4#issuecomment-516738205) to [this previous issue](https://github.com/hassony2/obman_train/issues/4) helps ?

Let me know !

Best,

Yana
